language: python

python:
  - "3.6"

env:
  - GPYTORCH_VERSION=stable
  - GPYTORCH_VERSION=master

install:
  - pip install cython numpy scipy pytest black
  - if [[ $GPYTORCH_VERSION = "stable" ]]; then
      pip install gpytorch;
    else
      pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html;
      pip install git+https://github.com/cornellius-gp/gpytorch.git;
    fi
  - pip install -e .

script:
  - black --check --diff .
  - python -c "import gpytorch; print('Testing with GPyTorch Version:' + ' ' +  gpytorch.__version__)"
  - pytest -ra
